application: gilpa
version: 2
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /media
  static_dir: _generated_media

- url: /admin/.*
  script: common/appenginepatch/main.py
  login: admin

- url: /.*
  script: common/appenginepatch/main.py
