application: geo-tweet
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /static
  static_dir: static

- url: /js
  static_dir: js

- url: /images
  static_dir: images
  
- url: /twitter/.*
  script: twitter_oauth_handler.py
  
- url: /.*
  script: geo_tweet.py
